-- 간단한 방법: Foreign Key 체크를 끄고 타입 변경 후 다시 켜기

SET FOREIGN_KEY_CHECKS = 0;

-- ID 컬럼 타입을 BIGINT로 변경
ALTER TABLE companies MODIFY COLUMN id BIGINT AUTO_INCREMENT;
ALTER TABLE categories MODIFY COLUMN id BIGINT AUTO_INCREMENT;
ALTER TABLE categories MODIFY COLUMN company_id BIGINT NOT NULL;
ALTER TABLE products MODIFY COLUMN id BIGINT AUTO_INCREMENT;
ALTER TABLE products MODIFY COLUMN company_id BIGINT NOT NULL;
ALTER TABLE products MODIFY COLUMN category_id BIGINT NOT NULL;
ALTER TABLE options MODIFY COLUMN id BIGINT AUTO_INCREMENT;
ALTER TABLE options MODIFY COLUMN company_id BIGINT NOT NULL;
ALTER TABLE options MODIFY COLUMN category_id BIGINT;
ALTER TABLE product_variants MODIFY COLUMN id BIGINT AUTO_INCREMENT;
ALTER TABLE product_variants MODIFY COLUMN product_id BIGINT NOT NULL;
ALTER TABLE price_matrix MODIFY COLUMN id BIGINT AUTO_INCREMENT;
ALTER TABLE price_matrix MODIFY COLUMN product_id BIGINT NOT NULL;

SET FOREIGN_KEY_CHECKS = 1;





